### ISSUE TITLE
Maintain plugin together with atto_morefontcolors

### ISSUE THREAD

**Issue by abias** [ndunand/moodle-atto_morebackcolors#10]
Hi Nicolas,

I have seen that, while you maintain the plugin atto_morefontcolors quite regularly, this plugin has become quite outdated. It still works, but it looks unmaintained while there are 2.500+ installations out there according to https://moodle.org/plugins/atto_morebackcolors.

Would you mind to maintain both plugins together again?

Thanks in advance of all community members who run both plugins together!

Cheers,
Alex

**Comment by ndunand** [comment]
Hi Alex,

Thanks for bringing this to my attention. Could you please elaborate on what you mean by "it looks unmaintained"?

Both plugins are 100% equivalent, support the latest Moodle version, and differ only by the last CSS fix I pushed yesterday to the `morefontcolors` plugin.

This plugin will be playing catch-up shortly on the aforementioned fix.

**Comment by abias** [comment]
Hi Nicolas,

> Could you please elaborate on what you mean by "it looks unmaintained"?

Oh. I think I should have looked more closer before posting this issue.

I _thought_ that atto_morefontcolors would be much more up-to-date as I saw on moodle.org/plugins today that it was released for Moodle up to 3.11 while atto_morebackcolors was released for Moodle up to 3.5 only.

However, after reading your response, I saw now that atto_morefontcolors was just updated by you after 3 years as well and I was wrong assuming that the one is maintained and the other one is not.

Sorry for the disturbance. I will wait patiently for a new official release of atto_morebackcolors and please keep up the good work!

Cheers,
Alex

**Comment by ndunand** [comment]
Hi Alex,

No worries, this actually reminded to to push this tiny fix (d0246c911df63a) to this plugin as well.

They are now in sync again as per now.

Cheers,
Nicolas
