### ISSUE TITLE
Moodle 4 support

### ISSUE THREAD

**Issue by acquaalta** [ndunand/moodle-atto_morebackcolors#11]
Hi,
Could you please add support for Moodle 4?
Even if the current version of the plugin would work on Moodle 4, an official support would be great.

Thanks even for considering it :-)

**Comment by NicoAlexH** [comment]
Hi, we've just made the plugin officially compatible with Moodle 4.1 :)

**Comment by acquaalta** [comment]
Thank you very much :-)
