### ISSUE TITLE
Dropdown menu width too small, with Adaptable theme

### ISSUE THREAD

**Issue by matcho** [ndunand/moodle-atto_morebackcolors#5]
When used with adaptable theme, the dropdown menu is broken and the color squares are hidden.
The CSS rule responsible for that is:
`.atto_backcolor_button .dropdown-menu {
    min-width: inherit;
}`
Manually setting a min-width of 50px fixes it :
`.atto_backcolor_button .dropdown-menu {
    min-width: 50px;
}`
A bug was filed to Adaptable theme maintainers : https://bitbucket.org/covuni/moodle-theme_adaptable/issues/385/atto-plugins-dropdown-menus-broken and an issue to atto_morefontcolors that also suffers from this problem : https://github.com/ndunand/moodle-atto_morefontcolors/issues/9

Greetings,
Mathias

**Comment by ndunand** [comment]
This should be addressed by the new version, feel free to reopen if needed.
